# Array

# 1-D array

In [1]:
a = [1,2,3]
type(a)

list

In [2]:
import numpy as np

In [3]:
a1 = np.array(a)
a1

array([1, 2, 3])

In [4]:
type(np.array(a))

numpy.ndarray

# 2-D array

In [5]:
b = [1,4,9]

In [6]:
a2 = np.array([a,b])
a2

array([[1, 2, 3],
       [1, 4, 9]])

In [7]:
type(a2)

numpy.ndarray

In [8]:
a2.ndim

2

In [9]:
a1 = np.array([[[[1, 2, 3],[1,4,9],[1,5,9]]],[[1,9,8],[4,4,5],[5,5,8]]])

<ipython-input-9-5084c852b38d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[[[1, 2, 3],[1,4,9],[1,5,9]]],[[1,9,8],[4,4,5],[5,5,8]]])


In [10]:
a1.shape

(2,)

In [11]:
a2 = np.array([[[[2, 3,4,5],[3, 4,5,9]],[[5, 6,8,7], [8, 9,7,8]]]])
print(a2.shape)

(1, 2, 2, 4)


In [12]:
#a3 = np.ones[1]

In [13]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(1,6) #creat equally spaced value

array([1, 2, 3, 4, 5])

In [15]:
np.arange(1,6,2) #2 is called step

array([1, 3, 5])

In [16]:
np.arange(1,6,3)

array([1, 4])

In [17]:
np.linspace(start=10,stop=30,num=20)

array([10.        , 11.05263158, 12.10526316, 13.15789474, 14.21052632,
       15.26315789, 16.31578947, 17.36842105, 18.42105263, 19.47368421,
       20.52631579, 21.57894737, 22.63157895, 23.68421053, 24.73684211,
       25.78947368, 26.84210526, 27.89473684, 28.94736842, 30.        ])

In [18]:
a = np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
a.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.array([[1,2],[2,3]])
b = np.array([[0,0],[1,1]])

In [24]:
a

array([[1, 2],
       [2, 3]])

In [25]:
b

array([[0, 0],
       [1, 1]])

In [26]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 0, 1],
       [2, 3, 0, 1]])

In [27]:
b

array([[0, 0],
       [1, 1]])

In [28]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [2, 3],
       [0, 0],
       [1, 1]])

In [29]:
np.concatenate((a,b),axis=None)

array([1, 2, 2, 3, 0, 0, 1, 1])

In [30]:
np.vstack((a,b))

array([[1, 2],
       [2, 3],
       [0, 0],
       [1, 1]])

In [31]:
c =np.hstack((a,b.T))

In [32]:
c.shape

(2, 4)

In [33]:
c

array([[1, 2, 0, 1],
       [2, 3, 0, 1]])

In [34]:
c.flatten()

array([1, 2, 0, 1, 2, 3, 0, 1])

In [35]:
d = np.array([[[0],[1],[2]],[[4],[5],[3]]])

In [36]:
d

array([[[0],
        [1],
        [2]],

       [[4],
        [5],
        [3]]])

In [37]:
d.shape

(2, 3, 1)

In [38]:
s = np.squeeze(d)

In [39]:
s.shape

(2, 3)

In [40]:
s

array([[0, 1, 2],
       [4, 5, 3]])

In [41]:
a

array([[1, 2],
       [2, 3]])

In [42]:
np.unique(a,axis=1)

array([[1, 2],
       [2, 3]])

In [43]:
np.unique(s,axis=0)

array([[0, 1, 2],
       [4, 5, 3]])

In [44]:
a = np.array([1,2,3])

In [45]:
a

array([1, 2, 3])

In [46]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [47]:
b =np.cos(a)

In [48]:
b

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [49]:
np.floor(b)

array([ 0., -1., -1.])

In [50]:
np.ceil(b)

array([ 1., -0., -0.])

In [51]:
np.round(b,3)

array([ 0.54 , -0.416, -0.99 ])

In [52]:
np.round(b,2)

array([ 0.54, -0.42, -0.99])

In [53]:
np.rint(b)

array([ 1., -0., -1.])

In [54]:
a = np.array([[1,2],[2,3],[3,4]])

In [55]:
a.shape

(3, 2)

In [56]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [57]:
b = np.sin(a)

In [58]:
b

array([[ 0.84147098,  0.90929743],
       [ 0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 ]])

In [59]:
np.floor(b)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0., -1.]])

In [60]:
np.ceil(b)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1., -0.]])

In [61]:
np.round(b,2)

array([[ 0.84,  0.91],
       [ 0.91,  0.14],
       [ 0.14, -0.76]])

In [62]:
np.sin(np.deg2rad(90))

1.0

In [63]:
np.sin(np.rad2deg(90))

-0.9540914674728181

In [64]:
a = np.linspace(1,5,4).reshape(2,2)

In [65]:
a

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

In [66]:
np.sum(a)

12.0

In [67]:
np.sum(a,axis=0)

array([4.66666667, 7.33333333])

In [68]:
np.sum(a,axis=1)

array([3.33333333, 8.66666667])

In [69]:
b = np.linspace(2,6,4).reshape(2,2)

In [70]:
b

array([[2.        , 3.33333333],
       [4.66666667, 6.        ]])

In [71]:
a+b

array([[ 3.        ,  5.66666667],
       [ 8.33333333, 11.        ]])

In [72]:
a*b

array([[ 2.        ,  7.77777778],
       [17.11111111, 30.        ]])

In [73]:
np.round((a*b),2)

array([[ 2.  ,  7.78],
       [17.11, 30.  ]])

In [74]:
c = np.array([[1],[2]])

In [75]:
c

array([[1],
       [2]])

In [76]:
a+c #broadcasting

array([[2.        , 3.33333333],
       [5.66666667, 7.        ]])

In [77]:
x= np.array([[2,3,4,5],[5,6,7,8],[8,9,10,11]])

In [78]:
#b = np.array([[1,4],[2,5],[3,6]])

In [79]:
y = np.array([[2,3,4,5],[5,6,7,8],[8,9,10,11]])

In [80]:
x.shape

(3, 4)

In [81]:
y.shape

(3, 4)

In [82]:
x+y

array([[ 4,  6,  8, 10],
       [10, 12, 14, 16],
       [16, 18, 20, 22]])

In [83]:
np.prod(x)

1596672000

In [84]:
a

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

In [85]:
np.prod(x,axis=0)

array([ 80, 162, 280, 440])

In [86]:
np.sqrt(x)

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [87]:
a = np.arange(9).reshape(3,3)

In [88]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
b = np.linspace(start=10, stop=15,num=9).reshape(3,3)

In [90]:
b

array([[10.   , 10.625, 11.25 ],
       [11.875, 12.5  , 13.125],
       [13.75 , 14.375, 15.   ]])

In [91]:
#b.reshape(2,3)

In [92]:
np.concatenate((a,b),axis=0)

array([[ 0.   ,  1.   ,  2.   ],
       [ 3.   ,  4.   ,  5.   ],
       [ 6.   ,  7.   ,  8.   ],
       [10.   , 10.625, 11.25 ],
       [11.875, 12.5  , 13.125],
       [13.75 , 14.375, 15.   ]])