# Array

# 1-D array

In [1]:
a = [1,2,3]
type(a)

list

In [2]:
import numpy as np

In [3]:
a1 = np.array(a)
a1

array([1, 2, 3])

In [4]:
type(np.array(a))

numpy.ndarray

# 2-D array

In [5]:
b = [1,4,9]

In [6]:
a2 = np.array([a,b])
a2

array([[1, 2, 3],
       [1, 4, 9]])

In [7]:
type(a2)

numpy.ndarray

In [8]:
a2.ndim

2

In [9]:
a1 = np.array([[[[1, 2, 3],[1,4,9],[1,5,9]]],[[1,9,8],[4,4,5],[5,5,8]]])

<ipython-input-9-5084c852b38d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[[[1, 2, 3],[1,4,9],[1,5,9]]],[[1,9,8],[4,4,5],[5,5,8]]])


In [10]:
a1.shape

(2,)

In [11]:
a2 = np.array([[[[2, 3,4,5],[3, 4,5,9]],[[5, 6,8,7], [8, 9,7,8]]]])
print(a2.shape)

(1, 2, 2, 4)


In [12]:
#a3 = np.ones[1]

In [13]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(1,6) #creat equally spaced value

array([1, 2, 3, 4, 5])

In [15]:
np.arange(1,6,2) #2 is called step

array([1, 3, 5])

In [16]:
np.arange(1,6,3)

array([1, 4])

In [17]:
np.linspace(start=10,stop=30,num=20)

array([10.        , 11.05263158, 12.10526316, 13.15789474, 14.21052632,
       15.26315789, 16.31578947, 17.36842105, 18.42105263, 19.47368421,
       20.52631579, 21.57894737, 22.63157895, 23.68421053, 24.73684211,
       25.78947368, 26.84210526, 27.89473684, 28.94736842, 30.        ])

In [18]:
a = np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
a.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.array([[1,2],[2,3]])
b = np.array([[0,0],[1,1]])

In [24]:
a

array([[1, 2],
       [2, 3]])

In [25]:
b

array([[0, 0],
       [1, 1]])

In [26]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 0, 1],
       [2, 3, 0, 1]])

In [27]:
b

array([[0, 0],
       [1, 1]])

In [28]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [2, 3],
       [0, 0],
       [1, 1]])

In [29]:
np.concatenate((a,b),axis=None)

array([1, 2, 2, 3, 0, 0, 1, 1])

In [30]:
np.vstack((a,b))

array([[1, 2],
       [2, 3],
       [0, 0],
       [1, 1]])

In [31]:
c =np.hstack((a,b.T))

In [32]:
c.shape

(2, 4)

In [33]:
c

array([[1, 2, 0, 1],
       [2, 3, 0, 1]])

In [34]:
c.flatten()

array([1, 2, 0, 1, 2, 3, 0, 1])

In [35]:
d = np.array([[[0],[1],[2]],[[4],[5],[3]]])

In [36]:
d

array([[[0],
        [1],
        [2]],

       [[4],
        [5],
        [3]]])

In [37]:
d.shape

(2, 3, 1)

In [38]:
s = np.squeeze(d)

In [39]:
s.shape

(2, 3)

In [40]:
s

array([[0, 1, 2],
       [4, 5, 3]])

In [41]:
a

array([[1, 2],
       [2, 3]])

In [42]:
np.unique(a,axis=1)

array([[1, 2],
       [2, 3]])

In [43]:
np.unique(s,axis=0)

array([[0, 1, 2],
       [4, 5, 3]])

In [44]:
a = np.array([1,2,3])

In [45]:
a

array([1, 2, 3])

In [46]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [47]:
b =np.cos(a)

In [48]:
b

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [49]:
np.floor(b)

array([ 0., -1., -1.])

In [50]:
np.ceil(b)

array([ 1., -0., -0.])

In [51]:
np.round(b,3)

array([ 0.54 , -0.416, -0.99 ])

In [52]:
np.round(b,2)

array([ 0.54, -0.42, -0.99])

In [53]:
np.rint(b)

array([ 1., -0., -1.])

In [54]:
a = np.array([[1,2],[2,3],[3,4]])

In [55]:
a.shape

(3, 2)

In [56]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [57]:
b = np.sin(a)

In [58]:
b

array([[ 0.84147098,  0.90929743],
       [ 0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 ]])

In [59]:
np.floor(b)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0., -1.]])

In [60]:
np.ceil(b)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1., -0.]])

In [61]:
np.round(b,2)

array([[ 0.84,  0.91],
       [ 0.91,  0.14],
       [ 0.14, -0.76]])

In [62]:
np.sin(np.deg2rad(90))

1.0

In [63]:
np.sin(np.rad2deg(90))

-0.9540914674728181

In [64]:
a = np.linspace(1,5,4).reshape(2,2)

In [65]:
a

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

In [66]:
np.sum(a)

12.0

In [67]:
np.sum(a,axis=0)

array([4.66666667, 7.33333333])

In [68]:
np.sum(a,axis=1)

array([3.33333333, 8.66666667])

In [69]:
b = np.linspace(2,6,4).reshape(2,2)

In [70]:
b

array([[2.        , 3.33333333],
       [4.66666667, 6.        ]])

In [71]:
a+b

array([[ 3.        ,  5.66666667],
       [ 8.33333333, 11.        ]])

In [72]:
a*b

array([[ 2.        ,  7.77777778],
       [17.11111111, 30.        ]])

In [73]:
np.round((a*b),2)

array([[ 2.  ,  7.78],
       [17.11, 30.  ]])

In [74]:
c = np.array([[1],[2]])

In [75]:
c

array([[1],
       [2]])

In [76]:
a+c #broadcasting

array([[2.        , 3.33333333],
       [5.66666667, 7.        ]])

In [77]:
x= np.array([[2,3,4,5],[5,6,7,8],[8,9,10,11]])

In [78]:
#b = np.array([[1,4],[2,5],[3,6]])

In [79]:
y = np.array([[2,3,4,5],[5,6,7,8],[8,9,10,11]])

In [80]:
x.shape

(3, 4)

In [81]:
y.shape

(3, 4)

In [82]:
x+y

array([[ 4,  6,  8, 10],
       [10, 12, 14, 16],
       [16, 18, 20, 22]])

In [83]:
np.prod(x)

1596672000

In [84]:
a

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

In [85]:
np.prod(x,axis=0)

array([ 80, 162, 280, 440])

In [86]:
np.sqrt(x)

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [87]:
a = np.arange(9).reshape(3,3)

In [88]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
b = np.linspace(start=10, stop=15,num=9).reshape(3,3)

In [90]:
b

array([[10.   , 10.625, 11.25 ],
       [11.875, 12.5  , 13.125],
       [13.75 , 14.375, 15.   ]])

In [91]:
#b.reshape(2,3)

In [92]:
np.concatenate((a,b),axis=0)

array([[ 0.   ,  1.   ,  2.   ],
       [ 3.   ,  4.   ,  5.   ],
       [ 6.   ,  7.   ,  8.   ],
       [10.   , 10.625, 11.25 ],
       [11.875, 12.5  , 13.125],
       [13.75 , 14.375, 15.   ]])

In [93]:
#sorting 25-01-2023

In [94]:
a = np.array([[1,4],[3,1]])

In [95]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [96]:
np.sort(a, axis =0)

array([[1, 1],
       [3, 4]])

In [97]:
np.sort(a, axis =1)

array([[1, 4],
       [1, 3]])

In [98]:
np.sort(a, axis =None)

array([1, 1, 3, 4])

In [99]:
a[0,1]

4

In [100]:
b = np.array([33,11,22])

In [101]:
b

array([33, 11, 22])

In [102]:
np.sort(b)

array([11, 22, 33])

In [103]:
np.argsort(b) #give the order of index at which it sort

array([1, 2, 0], dtype=int64)

In [104]:
x = np.array([[5,6,7],[7,8,9]])

In [105]:
x

array([[5, 6, 7],
       [7, 8, 9]])

In [106]:
np.sort(x)

array([[5, 6, 7],
       [7, 8, 9]])

In [107]:
np.argsort(x)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [108]:
c = np.random.randint(1,20,10).reshape(2,5)

In [109]:
c

array([[16, 13, 11, 13,  2],
       [ 6, 14,  4,  5,  8]])

In [110]:
np.argmax(c) #faltten the array then give the location of max value by indexing

0

In [111]:
np.argmax(c, axis =0)

array([0, 1, 0, 0, 1], dtype=int64)

In [112]:
np.argmax(c, axis =1)

array([0, 1], dtype=int64)

In [113]:
np.argmin(c)

4

In [114]:
np.argmin(c, axis=1)

array([4, 2], dtype=int64)

In [115]:
a = np.array([[[1,5,4,8,9],[5,4,8,9,8],[8,7,9,4,15]]])

In [116]:
a.shape

(1, 3, 5)

In [117]:
np.argmax(a)

14

In [118]:
np.argmin(a)

0

In [119]:
a = np.random.random((3,3,5))

In [120]:
a.shape

(3, 3, 5)

In [121]:
a

array([[[0.93629255, 0.32886831, 0.87185447, 0.9076769 , 0.41968201],
        [0.42389307, 0.04946246, 0.66503149, 0.27418709, 0.65344461],
        [0.35447159, 0.48577247, 0.1596004 , 0.44716984, 0.22751774]],

       [[0.69463227, 0.87882053, 0.74785622, 0.30675422, 0.30539311],
        [0.27591997, 0.80592857, 0.46333662, 0.01519297, 0.47581565],
        [0.93222271, 0.54636192, 0.84885303, 0.09696353, 0.45631633]],

       [[0.87121374, 0.64201399, 0.93529473, 0.74446839, 0.9701816 ],
        [0.57475524, 0.97309099, 0.9266001 , 0.27060132, 0.34541955],
        [0.93054559, 0.23419489, 0.7720783 , 0.53732079, 0.8150146 ]]])

In [122]:
np.argmax(a)

36

In [123]:
np.argmin(a)

23

In [124]:
b = np.random.randint(5,50,45).reshape(3,3,5)

In [125]:
b.shape

(3, 3, 5)

In [126]:
np.max(b)

48

In [127]:
np.argmax(b)

2

In [128]:
#conditional array

In [129]:
b

array([[[13, 41, 48, 26, 40],
        [31, 35,  8, 26, 12],
        [33,  9, 12, 31,  9]],

       [[24, 23,  8, 32,  5],
        [24, 35, 36,  6, 11],
        [35, 28, 34,  7, 37]],

       [[ 8, 31, 34, 41, 43],
        [30, 29, 44, 42, 16],
        [43,  7, 22, 43, 21]]])

In [130]:
c

array([[16, 13, 11, 13,  2],
       [ 6, 14,  4,  5,  8]])

In [131]:
np.where(c<9)

(array([0, 1, 1, 1, 1], dtype=int64), array([4, 0, 2, 3, 4], dtype=int64))

# Linear algebra

In [132]:
v1 = np.arange(3)

In [133]:
v1

array([0, 1, 2])

In [134]:
m1 = np.arange(6).reshape(2,3)

In [135]:
m1

array([[0, 1, 2],
       [3, 4, 5]])

In [136]:
v2 = np.array([5,6,7])

In [137]:
m2 = np.array([[1,4,6],[2,3,4]])

In [138]:
v1+v2

array([5, 7, 9])

In [139]:
v1-v2

array([-5, -5, -5])

In [140]:
m1+m2

array([[1, 5, 8],
       [5, 7, 9]])

In [141]:
np.add(v1,v2) #to add elements of diiffrent array(sum add elements of same array)

array([5, 7, 9])

In [142]:
np.dot(v1,v2)

20

In [143]:
np.dot(m1,m2.T)

array([[16, 11],
       [49, 38]])

In [144]:
np.matmul(m1,m2.T) #matrix must be compatible

array([[16, 11],
       [49, 38]])

In [145]:
m1@m2.reshape(3,2)

array([[12, 10],
       [42, 40]])

In [146]:
v3 = np.array([2,3])

In [147]:
np.linalg.norm(v3) #magnitude of vector

3.605551275463989

In [148]:
np.linalg.norm(v3,1) #manhatton norm

5.0

In [149]:
np.linalg.norm(v3,3) #manhatton norm(L1,L2,L3)

3.2710663101885897

In [150]:
np.transpose(m2)

array([[1, 2],
       [4, 3],
       [6, 4]])

In [151]:
m2.T

array([[1, 2],
       [4, 3],
       [6, 4]])

In [152]:
m2.reshape(3,2)

array([[1, 4],
       [6, 2],
       [3, 4]])

In [153]:
p = np.arange(2,6)

In [154]:
p

array([2, 3, 4, 5])

In [155]:
p.T #1D array not transposed

array([2, 3, 4, 5])

In [156]:
p = np.arange(2,6).reshape(1,4)

In [157]:
p.T

array([[2],
       [3],
       [4],
       [5]])

In [158]:
np.trace(m2)

4

In [159]:
sum(m2.diagonal())

4

In [160]:
np.linalg.matrix_rank(m2)

2

# Statistics

In [161]:
#discripetive 

In [162]:
a = np.array([1,2,3,4,5,6,7,9]).reshape(2,4)

In [163]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [164]:
b =np.mean(a, axis=1)

In [165]:
b[0]

2.5

In [166]:
b = np.array([[1,2,3],[4,5,6]])

In [167]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
np.median(b)

3.5

In [169]:
np.median(b, axis=0)

array([2.5, 3.5, 4.5])

In [170]:
a = np.array([1,2,3,3,4,5,5,5,5,5]) #mode calculation

In [171]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [172]:
val,count = np.unique(a, return_counts =True)

In [173]:
count

array([1, 1, 2, 1, 5], dtype=int64)

In [174]:
val

array([1, 2, 3, 4, 5])

In [175]:
mode= np.argmax(count)

In [176]:
mode

4

In [177]:
print("the mode of data is:",val[mode] )

the mode of data is: 5


In [178]:
np.var(a)

1.9600000000000002

In [179]:
b = np.array([3,4,7,8])

In [180]:
np.var(b)

4.25

In [181]:
np.std(a)

1.4000000000000001

In [182]:
np.std(b)

2.0615528128088303

In [183]:
np.amin(b)

3

In [184]:
np.amax(b)

8

In [185]:
np.average(b)

5.5

In [186]:
np.mean(b)

5.5

In [187]:
c= np.array([5,6,7])
w = np.array([8,2,3])

In [188]:
np.average(c)

6.0

In [189]:
np.mean(c)

6.0

In [190]:
np.average(c, weights =w)

5.615384615384615

In [1]:
a=12
b=23
if a* b>1000:
      print( “product=” ,a*b)
else :
      print( “sum=”, a+b)
#Check the if the if the given code is correct .

SyntaxError: invalid character in identifier (<ipython-input-1-08381b7f872e>, line 4)