In [1]:
import csv

In [2]:
import numpy as np

In [3]:
data = []

In [4]:
with open("SampleTemperature Sheet - Sheet1.csv", 'r') as x:
    data = list(csv.reader(x, delimiter=","))

### 1. Data representation in appropriate Numpy

In [5]:
#Filling the missing values with suitable terms using masking

In [6]:
data = np.array(data)
display(data)

array([['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['', 'Week 2', '9', '21', '9', '23', '14', '21', '-13', '23',
        '11', '23', '10', '26', '6', '27'],
       ['', 'Week 3', '9', '32', '15', '22', '13', '21', '13', '28', '6',
        '26', '15', '24', '12', '29'],
       ['', 'Week 4', '13', '26', '6', '28', '15', '20', '9', '30', '13',
        '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['', 'Week 2', '11', '28', '11', '25', '12', '23', '13', '23',
        '6'

In [7]:
Index = data[0:2,:] #make a array wich contains all index values

In [8]:
Index

array([['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U9')

In [9]:
Index[0,3] = 'Monday'
Index[0,5] = 'Tuesday'
Index[0,7] = 'Wednesday'
Index[0,9] = 'Thursday'
Index[0,11] = 'Friday'
Index[0,13] = 'Saturday'
Index[0,15] = 'Sunday'
Index[1,0] = 'Month'
Index[1,1] = 'Week'
Index 
#filling all missing values of index with suitable ones

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U9')

In [10]:
Nov_data = data[2:6,0:]
Nov_data #make a array of data set contains only november month data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['', 'Week 2', '9', '21', '9', '23', '14', '21', '-13', '23',
        '11', '23', '10', '26', '6', '27'],
       ['', 'Week 3', '9', '32', '15', '22', '13', '21', '13', '28', '6',
        '26', '15', '24', '12', '29'],
       ['', 'Week 4', '13', '26', '6', '28', '15', '20', '9', '30', '13',
        '31', '7', '32', '15', '27']], dtype='<U9')

In [11]:
Nov_data.shape

(4, 16)

In [12]:
Nov_data[1:4,0] = 'November' #fiiling the missing value with November value

In [13]:
Nov_data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [14]:
Dec_data = data[6:10,0:]
Dec_data #make a array of data set contains only december month data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['', 'Week 2', '11', '28', '11', '25', '12', '23', '13', '23',
        '6', '25', '14', '25', '14', '26'],
       ['', 'Week 3', '8', '30', '12', '32', '6', '30', '11', '28', '11',
        '27', '15', '26', '8', '20'],
       ['', 'Week 4', '11', '29', '11', '27', '12', '28', '10', '22',
        '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [15]:
Dec_data[1:4,0] = 'December' #fiiling the missing value with december value

In [16]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [17]:
Jan_data = data[10:14,0:]
Jan_data #make a array of data set contains only january month data

array([['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', '7'],
       ['', 'Week 2', '5', '18', '8', '19', '7', '18', '6', '19', '5',
        '18', '7', '6', '20', '5'],
       ['', 'Week 3', '2', '22', '7', '19', '4', '22', '2', '21', '8',
        '22', '4', '2', '21', '2'],
       ['', 'Week 4', '4', '22', '6', '18', '8', '22', '5', '18', '3',
        '22', '4', '8', '18', '7']], dtype='<U9')

In [18]:
Jan_data[1:4,0] = 'January'
Jan_data                        #fiiling the missing value with january value

array([['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', '7'],
       ['January', 'Week 2', '5', '18', '8', '19', '7', '18', '6', '19',
        '5', '18', '7', '6', '20', '5'],
       ['January', 'Week 3', '2', '22', '7', '19', '4', '22', '2', '21',
        '8', '22', '4', '2', '21', '2'],
       ['January', 'Week 4', '4', '22', '6', '18', '8', '22', '5', '18',
        '3', '22', '4', '8', '18', '7']], dtype='<U9')

In [19]:
Feb_data = data[14:18,0:]
Feb_data #make a array of data set contains only feburary month data

array([['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71', '22', '7'],
       ['', 'Week 2', '11', '18', '8', '21', '11', '22', '7', '19', '12',
        '19', '11', '8', '20', '8'],
       ['', 'Week 3', '12', '21', '10', '22', '7', '18', '8', '19', '9',
        '22', '7', '11', '18', '11'],
       ['', 'Week 4', '10', '22', '9', '18', '7', '19', '11', '18', '7',
        '21', '11', '7', '18', '12']], dtype='<U9')

In [20]:
Feb_data[1:4,0] = 'Febuary' #fiiling the missing value with feburary value
Feb_data

array([['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71', '22', '7'],
       ['Febuary', 'Week 2', '11', '18', '8', '21', '11', '22', '7',
        '19', '12', '19', '11', '8', '20', '8'],
       ['Febuary', 'Week 3', '12', '21', '10', '22', '7', '18', '8',
        '19', '9', '22', '7', '11', '18', '11'],
       ['Febuary', 'Week 4', '10', '22', '9', '18', '7', '19', '11',
        '18', '7', '21', '11', '7', '18', '12']], dtype='<U9')

In [21]:
data = np.vstack(((((Index,Nov_data,Dec_data,Jan_data,Feb_data)))))

In [22]:
data #make a final dataset contains all values with all values

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

### 2. Dimensions and shape of the array

In [23]:
data.shape #shape of array

(18, 16)

In [24]:
data.dtype.type

numpy.str_

In [25]:
data.ndim #dimension of array

2

### 3. The daily temperatures for the first week of each month

In [26]:
Nov_data #first print the nov month data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [27]:
Nov_Week1_max = Nov_data[0,2:].astype(int) #then select the first week on nov month

In [28]:
Nov_Week1_max

array([ 8, 21, 11, 20, 12, 30, 15, 20, 11, 31, 14, 20,  8, 26])

In [29]:
np.max(Nov_Week1_max) #then calculate max of that

31

In [30]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [31]:
Dec_Week1_max = Dec_data[0,2:].astype(int) #then select the first week on dec month
Dec_Week1_max

array([ 7, 32, 11, 31,  8, 27, 11, 25, 10, 31,  6, 24,  6, 31])

In [32]:
np.max(Dec_Week1_max) #then calculate max of that

32

In [33]:
Jan_data

array([['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', '7'],
       ['January', 'Week 2', '5', '18', '8', '19', '7', '18', '6', '19',
        '5', '18', '7', '6', '20', '5'],
       ['January', 'Week 3', '2', '22', '7', '19', '4', '22', '2', '21',
        '8', '22', '4', '2', '21', '2'],
       ['January', 'Week 4', '4', '22', '6', '18', '8', '22', '5', '18',
        '3', '22', '4', '8', '18', '7']], dtype='<U9')

In [34]:
Jan_Week1_max = Jan_data[0,2:].astype(int) #then select the first week on jan month
Jan_Week1_max

array([ 3, 19,  8, 22,  7, 18,  7, 22,  3, 19,  6,  8, 20,  7])

In [35]:
np.max(Jan_Week1_max) #then calculate max of that

22

In [36]:
Feb_data

array([['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71', '22', '7'],
       ['Febuary', 'Week 2', '11', '18', '8', '21', '11', '22', '7',
        '19', '12', '19', '11', '8', '20', '8'],
       ['Febuary', 'Week 3', '12', '21', '10', '22', '7', '18', '8',
        '19', '9', '22', '7', '11', '18', '11'],
       ['Febuary', 'Week 4', '10', '22', '9', '18', '7', '19', '11',
        '18', '7', '21', '11', '7', '18', '12']], dtype='<U9')

In [37]:
Feb_Week1_max = Feb_data[0,2:].astype(int) #then select the first week on feb month
Feb_Week1_max

array([ 10,  18,   9,  20, -10,  21,  11,  20,  12,  19,  12,  71,  22,
         7])

In [38]:
np.max(Feb_Week1_max) #then calculate max of that

71

### 4. Print the temperatures for Tuesday of each month

In [39]:
Tues_temp = data[2:,4:6]  #select tuesday value for all months

In [40]:
Tues_temp

array([['11', '20'],
       ['9', '23'],
       ['15', '22'],
       ['6', '28'],
       ['11', '31'],
       ['11', '25'],
       ['12', '32'],
       ['11', '27'],
       ['8', '22'],
       ['8', '19'],
       ['7', '19'],
       ['6', '18'],
       ['9', '20'],
       ['8', '21'],
       ['10', '22'],
       ['9', '18']], dtype='<U9')

In [41]:
Months = data[2:,0:2]

In [42]:
Tuesday_temp = np.hstack((Months,Tues_temp))
Tuesday_temp #then hstack the month and tuesday temp value

array([['November', 'Week 1', '11', '20'],
       ['November', 'Week 2', '9', '23'],
       ['November', 'Week 3', '15', '22'],
       ['November', 'Week 4', '6', '28'],
       ['December', 'Week 1', '11', '31'],
       ['December', 'Week 2', '11', '25'],
       ['December', 'Week 3', '12', '32'],
       ['December', 'Week 4', '11', '27'],
       ['January', 'Week 1', '8', '22'],
       ['January', 'Week 2', '8', '19'],
       ['January', 'Week 3', '7', '19'],
       ['January', 'Week 4', '6', '18'],
       ['February', 'Week 1', '9', '20'],
       ['Febuary', 'Week 2', '8', '21'],
       ['Febuary', 'Week 3', '10', '22'],
       ['Febuary', 'Week 4', '9', '18']], dtype='<U9')

### 5 .Print only the maximum temperature for all the weekdays of Dec and Feb.

In [43]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [44]:
Feb_data

array([['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71', '22', '7'],
       ['Febuary', 'Week 2', '11', '18', '8', '21', '11', '22', '7',
        '19', '12', '19', '11', '8', '20', '8'],
       ['Febuary', 'Week 3', '12', '21', '10', '22', '7', '18', '8',
        '19', '9', '22', '7', '11', '18', '11'],
       ['Febuary', 'Week 4', '10', '22', '9', '18', '7', '19', '11',
        '18', '7', '21', '11', '7', '18', '12']], dtype='<U9')

In [45]:
Index

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp']],
      dtype='<U9')

In [46]:
max_weekdays = np.vstack(((Index,Dec_data,Feb_data)))
max_weekdays
#vstack the value of index, dec and feb month data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28'],
       ['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71'

In [47]:
max_temp_weekdays = max_weekdays[:,3::2]
max_temp_weekdays
#print the max value of tem for two month for all day using slicing

array([['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        'Saturday', 'Sunday'],
       ['Max Temp', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp'],
       ['32', '31', '27', '25', '31', '24', '31'],
       ['28', '25', '23', '23', '25', '25', '26'],
       ['30', '32', '30', '28', '27', '26', '20'],
       ['29', '27', '28', '22', '21', '27', '28'],
       ['18', '20', '21', '20', '19', '71', '7'],
       ['18', '21', '22', '19', '19', '8', '8'],
       ['21', '22', '18', '19', '22', '11', '11'],
       ['22', '18', '19', '18', '21', '7', '12']], dtype='<U9')

### 6. Print all the days along with the week number in November when the minimum temperature was less than 8 degrees.

In [48]:
Nov_data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [49]:
Nov_temp_con1 = Nov_data[0,2:].astype(int)
Nov_temp_week1 = Nov_temp_con1<=8
#print the value of nov data with week one with temp<= 8

In [50]:
Nov_temp_con1

array([ 8, 21, 11, 20, 12, 30, 15, 20, 11, 31, 14, 20,  8, 26])

In [51]:
Nov_temp_week1 #only two condition

array([ True, False, False, False, False, False, False, False, False,
       False, False, False,  True, False])

In [52]:
Nov_temp_con2 = Nov_data[1,2:].astype(int)
Nov_temp_week2 = Nov_temp_con2<=8
#print the value of nov data with week two with temp<= 8

In [53]:
print("For week 2 on temp value:" ,Nov_temp_con2)

For week 2 on temp value: [  9  21   9  23  14  21 -13  23  11  23  10  26   6  27]


In [54]:
print("For week 2 on temp less than 8 cond:" ,Nov_temp_week2)

For week 2 on temp less than 8 cond: [False False False False False False  True False False False False False
  True False]


In [55]:
Nov_temp_con3 = Nov_data[2,2:].astype(int)
Nov_temp_week3 = Nov_temp_con3<=8
#print the value of nov data with week three with temp<= 8

In [56]:
print("For week 3 on temp value:" ,Nov_temp_con3)
print("For week 3 on temp less than 8 cond:" ,Nov_temp_week3)

For week 3 on temp value: [ 9 32 15 22 13 21 13 28  6 26 15 24 12 29]
For week 3 on temp less than 8 cond: [False False False False False False False False  True False False False
 False False]


In [57]:
Nov_temp_con4 = Nov_data[3,2:].astype(int)
Nov_temp_week4 = Nov_temp_con4<=8

In [58]:
print("For week 4 on temp value:" ,Nov_temp_con4)
print("For week 4 on temp less than 8 cond:" ,Nov_temp_week4)
#print the value of nov data with week four with temp<= 8

For week 4 on temp value: [13 26  6 28 15 20  9 30 13 31  7 32 15 27]
For week 4 on temp less than 8 cond: [False False  True False False False False False False False  True False
 False False]


### 7. Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.

In [59]:
New_con = np.vstack(((Index,Dec_data,Jan_data)))
New_con 
#print new condition using vstack on index, dec and jan data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28'],
       ['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', 

In [60]:
New_con1 = New_con[2:,3::2]
New_con1
#select only max temp data for both months using slicing

array([['32', '31', '27', '25', '31', '24', '31'],
       ['28', '25', '23', '23', '25', '25', '26'],
       ['30', '32', '30', '28', '27', '26', '20'],
       ['29', '27', '28', '22', '21', '27', '28'],
       ['19', '22', '18', '22', '19', '8', '7'],
       ['18', '19', '18', '19', '18', '6', '5'],
       ['22', '19', '22', '21', '22', '2', '2'],
       ['22', '18', '22', '18', '22', '8', '7']], dtype='<U9')

In [61]:
New_con1 = New_con1[:,:].reshape(7*8,) #the reshape this convert it into 1d array

In [62]:
New_con1.astype(int)

array([32, 31, 27, 25, 31, 24, 31, 28, 25, 23, 23, 25, 25, 26, 30, 32, 30,
       28, 27, 26, 20, 29, 27, 28, 22, 21, 27, 28, 19, 22, 18, 22, 19,  8,
        7, 18, 19, 18, 19, 18,  6,  5, 22, 19, 22, 21, 22,  2,  2, 22, 18,
       22, 18, 22,  8,  7])

In [63]:
Max_temp = New_con1.astype(int)>=20
Max_temp 
#then find the condition with max temp>= 20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True,  True, False, False,  True, False,  True, False,  True,
       False, False])

### 8. Check if there are any absurd values present in the dataset(like some temp which should not be present in the data)

In [64]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [65]:
#missing values or outlier

In [66]:
#there is not any missing values but some outliers like -13,-10

### 9.What strategy would you use to handle such data points?

In [67]:
#to handle outliers we calculate the inter qurtile range and then find the outliers and then fill that value with median

### 10. Find and print the indexes of all the outlier(unusual) values present in the above dataset.

In [68]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [69]:
outliers = data[2:,2:].astype(int)
outliers
#print all the temp values for all months

array([[  8,  21,  11,  20,  12,  30,  15,  20,  11,  31,  14,  20,   8,
         26],
       [  9,  21,   9,  23,  14,  21, -13,  23,  11,  23,  10,  26,   6,
         27],
       [  9,  32,  15,  22,  13,  21,  13,  28,   6,  26,  15,  24,  12,
         29],
       [ 13,  26,   6,  28,  15,  20,   9,  30,  13,  31,   7,  32,  15,
         27],
       [  7,  32,  11,  31,   8,  27,  11,  25,  10,  31,   6,  24,   6,
         31],
       [ 11,  28,  11,  25,  12,  23,  13,  23,   6,  25,  14,  25,  14,
         26],
       [  8,  30,  12,  32,   6,  30,  11,  28,  11,  27,  15,  26,   8,
         20],
       [ 11,  29,  11,  27,  12,  28,  10,  22,  11,  21,  12,  27,  10,
         28],
       [  3,  19,   8,  22,   7,  18,   7,  22,   3,  19,   6,   8,  20,
          7],
       [  5,  18,   8,  19,   7,  18,   6,  19,   5,  18,   7,   6,  20,
          5],
       [  2,  22,   7,  19,   4,  22,   2,  21,   8,  22,   4,   2,  21,
          2],
       [  4,  22,   6,  18,   8,  22,   5, 

In [70]:
outliers.shape

(16, 14)

In [71]:
outliers.reshape(16*14,)
#then covert it into 1d array

array([  8,  21,  11,  20,  12,  30,  15,  20,  11,  31,  14,  20,   8,
        26,   9,  21,   9,  23,  14,  21, -13,  23,  11,  23,  10,  26,
         6,  27,   9,  32,  15,  22,  13,  21,  13,  28,   6,  26,  15,
        24,  12,  29,  13,  26,   6,  28,  15,  20,   9,  30,  13,  31,
         7,  32,  15,  27,   7,  32,  11,  31,   8,  27,  11,  25,  10,
        31,   6,  24,   6,  31,  11,  28,  11,  25,  12,  23,  13,  23,
         6,  25,  14,  25,  14,  26,   8,  30,  12,  32,   6,  30,  11,
        28,  11,  27,  15,  26,   8,  20,  11,  29,  11,  27,  12,  28,
        10,  22,  11,  21,  12,  27,  10,  28,   3,  19,   8,  22,   7,
        18,   7,  22,   3,  19,   6,   8,  20,   7,   5,  18,   8,  19,
         7,  18,   6,  19,   5,  18,   7,   6,  20,   5,   2,  22,   7,
        19,   4,  22,   2,  21,   8,  22,   4,   2,  21,   2,   4,  22,
         6,  18,   8,  22,   5,  18,   3,  22,   4,   8,  18,   7,  10,
        18,   9,  20, -10,  21,  11,  20,  12,  19,  12,  71,  2

In [72]:
out_sort = np.sort(outliers.reshape(16*14,))
out_sort 
#then sort it

array([-13, -10,   2,   2,   2,   2,   3,   3,   3,   4,   4,   4,   4,
         5,   5,   5,   5,   6,   6,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   8,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   9,   9,   9,   9,   9,   9,
         9,  10,  10,  10,  10,  10,  10,  10,  11,  11,  11,  11,  11,
        11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,  11,
        11,  11,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,
        13,  13,  13,  13,  13,  14,  14,  14,  14,  15,  15,  15,  15,
        15,  15,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,
        18,  18,  18,  19,  19,  19,  19,  19,  19,  19,  19,  19,  19,
        20,  20,  20,  20,  20,  20,  20,  20,  20,  20,  21,  21,  21,
        21,  21,  21,  21,  21,  21,  21,  21,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  23,  2

In [73]:
Q1 = np.percentile(out_sort,25)
#then find the first quirtile value

In [74]:
Q3 = np.percentile(out_sort,75)
#then find the third quirtile value

In [75]:
IQR = Q3 -Q1
#then find the IQR value

In [76]:
IQR

14.0

In [77]:
 lower_range = Q1 - (1.5 * IQR)
 upper_range = Q3 + (1.5 * IQR)

In [78]:
print("the value of lower range:",lower_range)
print("the value of upper range:",upper_range)

the value of lower range: -13.0
the value of upper range: 43.0


In [79]:
outlier =[]
for x in out_sort:
    if ((x> upper_range) or (x<lower_range)):
         outlier.append(x)
print(' outlier in the dataset is', outlier)
#print the value of outlier

 outlier in the dataset is [71]


### 11.Replace the outliers with an appropriate value.

In [80]:
App_value = outliers.reshape(16*14,)

In [81]:
x

71

In [82]:
mad = np.median(abs(App_value-np.median(App_value)))
print(mad)
#print the value of median and then fill this value in the outlier value

7.0


### 12. Find the average max temperature for the winter months in Jaipur.

In [83]:
avg_max = np.vstack(((Index, Nov_data, Dec_data, Jan_data)))
avg_max

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [84]:
Avg_Temp = avg_max[2:,3::2].astype(int)
Avg_Temp
#print the max temp data of nov,dec,jan month using slicing

array([[21, 20, 30, 20, 31, 20, 26],
       [21, 23, 21, 23, 23, 26, 27],
       [32, 22, 21, 28, 26, 24, 29],
       [26, 28, 20, 30, 31, 32, 27],
       [32, 31, 27, 25, 31, 24, 31],
       [28, 25, 23, 23, 25, 25, 26],
       [30, 32, 30, 28, 27, 26, 20],
       [29, 27, 28, 22, 21, 27, 28],
       [19, 22, 18, 22, 19,  8,  7],
       [18, 19, 18, 19, 18,  6,  5],
       [22, 19, 22, 21, 22,  2,  2],
       [22, 18, 22, 18, 22,  8,  7]])

In [85]:
np.mean(Avg_Temp)

22.666666666666668

In [86]:
np.max(Avg_Temp)

32

### 13. Find the weekly min avg temp for the month of Dec in Jaipur

In [87]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [88]:
Dec_min_temp = Dec_data[:,2::2].astype(int)
Dec_min_temp
#print the min temp data using slicing

array([[ 7, 11,  8, 11, 10,  6,  6],
       [11, 11, 12, 13,  6, 14, 14],
       [ 8, 12,  6, 11, 11, 15,  8],
       [11, 11, 12, 10, 11, 12, 10]])

In [89]:
np.mean(Dec_min_temp)

10.285714285714286

### 14. Find the overall avg temp for the months Dec and Jan

In [90]:
Ovr_avg = np.vstack(((Index,Dec_data,Jan_data)))
Ovr_avg

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28'],
       ['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', 

In [91]:
Ovr_Avg = Ovr_avg[2:,2:].astype(int)
Ovr_Avg
#print the overall temp for dec and jan month

array([[ 7, 32, 11, 31,  8, 27, 11, 25, 10, 31,  6, 24,  6, 31],
       [11, 28, 11, 25, 12, 23, 13, 23,  6, 25, 14, 25, 14, 26],
       [ 8, 30, 12, 32,  6, 30, 11, 28, 11, 27, 15, 26,  8, 20],
       [11, 29, 11, 27, 12, 28, 10, 22, 11, 21, 12, 27, 10, 28],
       [ 3, 19,  8, 22,  7, 18,  7, 22,  3, 19,  6,  8, 20,  7],
       [ 5, 18,  8, 19,  7, 18,  6, 19,  5, 18,  7,  6, 20,  5],
       [ 2, 22,  7, 19,  4, 22,  2, 21,  8, 22,  4,  2, 21,  2],
       [ 4, 22,  6, 18,  8, 22,  5, 18,  3, 22,  4,  8, 18,  7]])

In [92]:
np.mean(Ovr_Avg)

15.107142857142858

### 15. Find the least temp experienced by the city in the month of Dec and Jan. Also print the exact date( Day/Week/Month) for the same.

In [93]:
Ovr_Avg = Ovr_avg[2:,2:].astype(int).reshape(14*8,)
Ovr_Avg
#convert the dec and jan month data as Q14. into 1d array and reshaped it and then find min and max value

array([ 7, 32, 11, 31,  8, 27, 11, 25, 10, 31,  6, 24,  6, 31, 11, 28, 11,
       25, 12, 23, 13, 23,  6, 25, 14, 25, 14, 26,  8, 30, 12, 32,  6, 30,
       11, 28, 11, 27, 15, 26,  8, 20, 11, 29, 11, 27, 12, 28, 10, 22, 11,
       21, 12, 27, 10, 28,  3, 19,  8, 22,  7, 18,  7, 22,  3, 19,  6,  8,
       20,  7,  5, 18,  8, 19,  7, 18,  6, 19,  5, 18,  7,  6, 20,  5,  2,
       22,  7, 19,  4, 22,  2, 21,  8, 22,  4,  2, 21,  2,  4, 22,  6, 18,
        8, 22,  5, 18,  3, 22,  4,  8, 18,  7])

In [94]:
np.min(Ovr_Avg)

2

In [95]:
np.argmin(Ovr_Avg)

84

### 16. Find the max temp in the month of Feb and return its date(Day/Week/Month)

In [96]:
Feb_data

array([['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
        '20', '12', '19', '12', '71', '22', '7'],
       ['Febuary', 'Week 2', '11', '18', '8', '21', '11', '22', '7',
        '19', '12', '19', '11', '8', '20', '8'],
       ['Febuary', 'Week 3', '12', '21', '10', '22', '7', '18', '8',
        '19', '9', '22', '7', '11', '18', '11'],
       ['Febuary', 'Week 4', '10', '22', '9', '18', '7', '19', '11',
        '18', '7', '21', '11', '7', '18', '12']], dtype='<U9')

In [97]:
Feb_max = Feb_data[:,2:].astype(int).reshape(14*4,)
Feb_max 
#print feb month data and convert it into 1d array

array([ 10,  18,   9,  20, -10,  21,  11,  20,  12,  19,  12,  71,  22,
         7,  11,  18,   8,  21,  11,  22,   7,  19,  12,  19,  11,   8,
        20,   8,  12,  21,  10,  22,   7,  18,   8,  19,   9,  22,   7,
        11,  18,  11,  10,  22,   9,  18,   7,  19,  11,  18,   7,  21,
        11,   7,  18,  12])

In [98]:
np.max(Feb_max )

71

In [99]:
np.argmax(Feb_max )

11

### 17. Find the days in the month of Nov where the max temp of the day dropped below the avg temp of the month.

In [100]:
Nov_con = np.vstack((Index,Nov_data))
Nov_con

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [101]:
Nov_con1 = Nov_con[0:6,3::2]
Nov_con1
#print the max temp for nov month data using slicing

array([['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        'Saturday', 'Sunday'],
       ['Max Temp', 'Max Temp', 'Max Temp', 'Max Temp', 'Max Temp',
        'Max Temp', 'Max Temp'],
       ['21', '20', '30', '20', '31', '20', '26'],
       ['21', '23', '21', '23', '23', '26', '27'],
       ['32', '22', '21', '28', '26', '24', '29'],
       ['26', '28', '20', '30', '31', '32', '27']], dtype='<U9')

In [102]:
Nov_con2 = Nov_con1[2:,].astype(int).reshape(7*4,)
Nov_con2 
#convert it into 1d array using reshaping

array([21, 20, 30, 20, 31, 20, 26, 21, 23, 21, 23, 23, 26, 27, 32, 22, 21,
       28, 26, 24, 29, 26, 28, 20, 30, 31, 32, 27])

In [103]:
np.mean(Nov_con2 )

25.285714285714285

In [104]:
Nov_con3 = Nov_con2 < np.mean(Nov_con2 )
Nov_con3
#find the condition for above question

array([ True,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False, False,  True, False, False, False,
       False])

### 18. Convert the above dataset into an array where the weeks of the same month must be present in the same row, but belonging to different months should come in a row either below or above the selected month.

In [105]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [106]:
Nov_data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [107]:
Nov_Week1 = Nov_data[0,:]
Nov_Week2 = Nov_data[1,:]
Nov_Week3 = Nov_data[2,:]
Nov_Week4 = Nov_data[3,:]
#print the data for all week for november month 

In [108]:
Nov_Week = np.hstack((((Nov_Week1,Nov_Week2,Nov_Week3,Nov_Week4))))
Nov_Week
#hstacking the all november month week data in one row

array(['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
       '20', '11', '31', '14', '20', '8', '26', 'November', 'Week 2', '9',
       '21', '9', '23', '14', '21', '-13', '23', '11', '23', '10', '26',
       '6', '27', 'November', 'Week 3', '9', '32', '15', '22', '13', '21',
       '13', '28', '6', '26', '15', '24', '12', '29', 'November',
       'Week 4', '13', '26', '6', '28', '15', '20', '9', '30', '13', '31',
       '7', '32', '15', '27'], dtype='<U9')

In [109]:
Dec_Week1 = Dec_data[0,:]
Dec_Week2 = Dec_data[1,:]
Dec_Week3 = Dec_data[2,:]
Dec_Week4 = Dec_data[3,:]
#print the data for all week for december month 

In [110]:
Dec_Week = np.hstack((((Dec_Week1,Dec_Week2,Dec_Week3,Dec_Week4))))
Dec_Week
#hstacking the all dec month week data in one row

array(['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11', '25',
       '10', '31', '6', '24', '6', '31', 'December', 'Week 2', '11', '28',
       '11', '25', '12', '23', '13', '23', '6', '25', '14', '25', '14',
       '26', 'December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
       '28', '11', '27', '15', '26', '8', '20', 'December', 'Week 4',
       '11', '29', '11', '27', '12', '28', '10', '22', '11', '21', '12',
       '27', '10', '28'], dtype='<U9')

In [111]:
Jan_Week1 = Jan_data[0,:]
Jan_Week2 = Jan_data[1,:]
Jan_Week3 = Jan_data[2,:]
Jan_Week4 = Jan_data[3,:]
#print the data for all week for january month 

In [112]:
Jan_Week = np.hstack((((Jan_Week1,Jan_Week2,Jan_Week3,Jan_Week4))))
Jan_Week
#hstacking the all jan month week data in one row

array(['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
       '3', '19', '6', '8', '20', '7', 'January', 'Week 2', '5', '18',
       '8', '19', '7', '18', '6', '19', '5', '18', '7', '6', '20', '5',
       'January', 'Week 3', '2', '22', '7', '19', '4', '22', '2', '21',
       '8', '22', '4', '2', '21', '2', 'January', 'Week 4', '4', '22',
       '6', '18', '8', '22', '5', '18', '3', '22', '4', '8', '18', '7'],
      dtype='<U9')

In [113]:
Feb_Week1 = Feb_data[0,:]
Feb_Week2 = Feb_data[1,:]
Feb_Week3 = Feb_data[2,:]
Feb_Week4 = Feb_data[3,:]
#print the data for all week for feburary month 

In [114]:
Feb_Week = np.hstack((((Feb_Week1,Feb_Week2,Feb_Week3,Feb_Week4))))
Feb_Week
#hstacking the all feb month week data in one row

array(['February', 'Week 1', '10', '18', '9', '20', '-10', '21', '11',
       '20', '12', '19', '12', '71', '22', '7', 'Febuary', 'Week 2', '11',
       '18', '8', '21', '11', '22', '7', '19', '12', '19', '11', '8',
       '20', '8', 'Febuary', 'Week 3', '12', '21', '10', '22', '7', '18',
       '8', '19', '9', '22', '7', '11', '18', '11', 'Febuary', 'Week 4',
       '10', '22', '9', '18', '7', '19', '11', '18', '7', '21', '11', '7',
       '18', '12'], dtype='<U9')

In [115]:
same_row = np.vstack((((Nov_Week,Dec_Week,Jan_Week,Feb_Week))))
same_row 
#vstack all the above calculated values

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26', 'November', 'Week 2',
        '9', '21', '9', '23', '14', '21', '-13', '23', '11', '23', '10',
        '26', '6', '27', 'November', 'Week 3', '9', '32', '15', '22',
        '13', '21', '13', '28', '6', '26', '15', '24', '12', '29',
        'November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31', 'December', 'Week 2',
        '11', '28', '11', '25', '12', '23', '13', '23', '6', '25', '14',
        '25', '14', '26', 'December', 'Week 3', '8', '30', '12', '32',
        '6', '30', '11', '28', '11', '27', '15', '26', '8', '20',
        'December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28'],
       ['January', 'Week 1', '3', '19', '8', '22', '7',

### 19. The above data is appropriate for an audience who follow the metric system of measurement. Create an array that holds the same data but presented in Fahrenheit.

In [116]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [117]:
Celcius = data[2:,2:].astype(int).reshape(16*14,)
Celcius
#print all the temp and convert into 1d array

array([  8,  21,  11,  20,  12,  30,  15,  20,  11,  31,  14,  20,   8,
        26,   9,  21,   9,  23,  14,  21, -13,  23,  11,  23,  10,  26,
         6,  27,   9,  32,  15,  22,  13,  21,  13,  28,   6,  26,  15,
        24,  12,  29,  13,  26,   6,  28,  15,  20,   9,  30,  13,  31,
         7,  32,  15,  27,   7,  32,  11,  31,   8,  27,  11,  25,  10,
        31,   6,  24,   6,  31,  11,  28,  11,  25,  12,  23,  13,  23,
         6,  25,  14,  25,  14,  26,   8,  30,  12,  32,   6,  30,  11,
        28,  11,  27,  15,  26,   8,  20,  11,  29,  11,  27,  12,  28,
        10,  22,  11,  21,  12,  27,  10,  28,   3,  19,   8,  22,   7,
        18,   7,  22,   3,  19,   6,   8,  20,   7,   5,  18,   8,  19,
         7,  18,   6,  19,   5,  18,   7,   6,  20,   5,   2,  22,   7,
        19,   4,  22,   2,  21,   8,  22,   4,   2,  21,   2,   4,  22,
         6,  18,   8,  22,   5,  18,   3,  22,   4,   8,  18,   7,  10,
        18,   9,  20, -10,  21,  11,  20,  12,  19,  12,  71,  2

In [118]:
print("Values in Centigrade degrees:")
print(Celcius)
print("Values in  Fahrenheit degrees:")
print(np.round((9*(Celcius)/5 + 32),2))
#convert the centigrade temp into fahrenhite using above formula

Values in Centigrade degrees:
[  8  21  11  20  12  30  15  20  11  31  14  20   8  26   9  21   9  23
  14  21 -13  23  11  23  10  26   6  27   9  32  15  22  13  21  13  28
   6  26  15  24  12  29  13  26   6  28  15  20   9  30  13  31   7  32
  15  27   7  32  11  31   8  27  11  25  10  31   6  24   6  31  11  28
  11  25  12  23  13  23   6  25  14  25  14  26   8  30  12  32   6  30
  11  28  11  27  15  26   8  20  11  29  11  27  12  28  10  22  11  21
  12  27  10  28   3  19   8  22   7  18   7  22   3  19   6   8  20   7
   5  18   8  19   7  18   6  19   5  18   7   6  20   5   2  22   7  19
   4  22   2  21   8  22   4   2  21   2   4  22   6  18   8  22   5  18
   3  22   4   8  18   7  10  18   9  20 -10  21  11  20  12  19  12  71
  22   7  11  18   8  21  11  22   7  19  12  19  11   8  20   8  12  21
  10  22   7  18   8  19   9  22   7  11  18  11  10  22   9  18   7  19
  11  18   7  21  11   7  18  12]
Values in  Fahrenheit degrees:
[ 46.4  69.8  51.8  68.   53.

In [119]:
Fahrenheit = np.round((9*(Celcius)/5 + 32),2).reshape(16,14)
Fahrenheit

array([[ 46.4,  69.8,  51.8,  68. ,  53.6,  86. ,  59. ,  68. ,  51.8,
         87.8,  57.2,  68. ,  46.4,  78.8],
       [ 48.2,  69.8,  48.2,  73.4,  57.2,  69.8,   8.6,  73.4,  51.8,
         73.4,  50. ,  78.8,  42.8,  80.6],
       [ 48.2,  89.6,  59. ,  71.6,  55.4,  69.8,  55.4,  82.4,  42.8,
         78.8,  59. ,  75.2,  53.6,  84.2],
       [ 55.4,  78.8,  42.8,  82.4,  59. ,  68. ,  48.2,  86. ,  55.4,
         87.8,  44.6,  89.6,  59. ,  80.6],
       [ 44.6,  89.6,  51.8,  87.8,  46.4,  80.6,  51.8,  77. ,  50. ,
         87.8,  42.8,  75.2,  42.8,  87.8],
       [ 51.8,  82.4,  51.8,  77. ,  53.6,  73.4,  55.4,  73.4,  42.8,
         77. ,  57.2,  77. ,  57.2,  78.8],
       [ 46.4,  86. ,  53.6,  89.6,  42.8,  86. ,  51.8,  82.4,  51.8,
         80.6,  59. ,  78.8,  46.4,  68. ],
       [ 51.8,  84.2,  51.8,  80.6,  53.6,  82.4,  50. ,  71.6,  51.8,
         69.8,  53.6,  80.6,  50. ,  82.4],
       [ 37.4,  66.2,  46.4,  71.6,  44.6,  64.4,  44.6,  71.6,  37.4,
         

### 20.Sort the above data in descending order on the basis of weekly average for the month of Dec.

In [120]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [121]:
Dec_week1 = Dec_data[0:1,2:].astype(int)
print("the value of week one:",Dec_week1)
Dec_week1_ase = np.mean(Dec_week1)
print("the mean value of week one:",np.mean(Dec_week1))
#print the value of week 1 and its mean value

the value of week one: [[ 7 32 11 31  8 27 11 25 10 31  6 24  6 31]]
the mean value of week one: 18.571428571428573


In [122]:
Dec_week2 = Dec_data[1,2:].astype(int)
print("the value of week two:",Dec_week2)
Dec_week2_ase = np.mean(Dec_week2)
print("the mean value of week two:",np.mean(Dec_week2))
#print the value of week 2 and its mean value

the value of week two: [11 28 11 25 12 23 13 23  6 25 14 25 14 26]
the mean value of week two: 18.285714285714285


In [123]:
Dec_week3 = Dec_data[2,2:].astype(int)
print("the value of week three:",Dec_week3)
Dec_week3_ase = np.mean(Dec_week3)
print("the mean value of week three:",np.mean(Dec_week3))
#print the value of week 3 and its mean value

the value of week three: [ 8 30 12 32  6 30 11 28 11 27 15 26  8 20]
the mean value of week three: 18.857142857142858


In [124]:
Dec_week4 = Dec_data[3,2:].astype(int)
print("the value of week four:",Dec_week4)
Dec_week4_ase = np.mean(Dec_week4)
print("the mean value of week four:",np.mean(Dec_week4))
#print the value of week 4 and its mean value

the value of week four: [11 29 11 27 12 28 10 22 11 21 12 27 10 28]
the mean value of week four: 18.5


In [125]:
Dec_week_ase = np.array((((Dec_week1_ase,Dec_week2_ase,Dec_week3_ase,Dec_week4_ase))))
Dec_week_ase
#make a new array with all week value of dec month

array([18.57142857, 18.28571429, 18.85714286, 18.5       ])

In [126]:
Dec_week_des = np.sort(Dec_week_ase)[::-1]
Dec_week_des
#sort the dec month value in desceding order

array([18.85714286, 18.57142857, 18.5       , 18.28571429])

### 21. Sort the temp of the first three days of each month in descending order on the basis of overall average for the whole winter.

In [127]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [128]:
three_days = data[2:-4, 2:8].astype(int).reshape(6*12,)
three_days
#print the value first three days of nov,dec,jan month and convert it into 1d array

array([ 8, 21, 11, 20, 12, 30,  9, 21,  9, 23, 14, 21,  9, 32, 15, 22, 13,
       21, 13, 26,  6, 28, 15, 20,  7, 32, 11, 31,  8, 27, 11, 28, 11, 25,
       12, 23,  8, 30, 12, 32,  6, 30, 11, 29, 11, 27, 12, 28,  3, 19,  8,
       22,  7, 18,  5, 18,  8, 19,  7, 18,  2, 22,  7, 19,  4, 22,  4, 22,
        6, 18,  8, 22])

In [129]:
a4 = (np.sort(three_days)[::-1])
#sort the first three days of nov,dec,jan month value in desceding order

In [130]:
Three_days  = np.mean(a4)
Three_days 
#print the mean of above value

16.51388888888889

### 22. Create an array that stores the difference between the min and max temp for each day in all the winter months.

In [131]:
winter_month = data[:-4,:]
winter_month
#print data of nov,dec and jan month

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [132]:
win_min = winter_month[2:,2::2].astype(int)
win_min
#print min temp value using slicing

array([[  8,  11,  12,  15,  11,  14,   8],
       [  9,   9,  14, -13,  11,  10,   6],
       [  9,  15,  13,  13,   6,  15,  12],
       [ 13,   6,  15,   9,  13,   7,  15],
       [  7,  11,   8,  11,  10,   6,   6],
       [ 11,  11,  12,  13,   6,  14,  14],
       [  8,  12,   6,  11,  11,  15,   8],
       [ 11,  11,  12,  10,  11,  12,  10],
       [  3,   8,   7,   7,   3,   6,  20],
       [  5,   8,   7,   6,   5,   7,  20],
       [  2,   7,   4,   2,   8,   4,  21],
       [  4,   6,   8,   5,   3,   4,  18]])

In [133]:
win_max = winter_month[2:,3::2].astype(int)
win_max
#print max temp value using slicing

array([[21, 20, 30, 20, 31, 20, 26],
       [21, 23, 21, 23, 23, 26, 27],
       [32, 22, 21, 28, 26, 24, 29],
       [26, 28, 20, 30, 31, 32, 27],
       [32, 31, 27, 25, 31, 24, 31],
       [28, 25, 23, 23, 25, 25, 26],
       [30, 32, 30, 28, 27, 26, 20],
       [29, 27, 28, 22, 21, 27, 28],
       [19, 22, 18, 22, 19,  8,  7],
       [18, 19, 18, 19, 18,  6,  5],
       [22, 19, 22, 21, 22,  2,  2],
       [22, 18, 22, 18, 22,  8,  7]])

In [134]:
diff = np.subtract(win_max,win_min)
diff
#find the subtract using two values

array([[ 13,   9,  18,   5,  20,   6,  18],
       [ 12,  14,   7,  36,  12,  16,  21],
       [ 23,   7,   8,  15,  20,   9,  17],
       [ 13,  22,   5,  21,  18,  25,  12],
       [ 25,  20,  19,  14,  21,  18,  25],
       [ 17,  14,  11,  10,  19,  11,  12],
       [ 22,  20,  24,  17,  16,  11,  12],
       [ 18,  16,  16,  12,  10,  15,  18],
       [ 16,  14,  11,  15,  16,   2, -13],
       [ 13,  11,  11,  13,  13,  -1, -15],
       [ 20,  12,  18,  19,  14,  -2, -19],
       [ 18,  12,  14,  13,  19,   4, -11]])

### 23. Find and store the difference between the max temp of two consecutive days for each month of winter season.

In [135]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['Month', 'Week', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27'],
       ['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6

In [136]:
Nov_data

array([['November', 'Week 1', '8', '21', '11', '20', '12', '30', '15',
        '20', '11', '31', '14', '20', '8', '26'],
       ['November', 'Week 2', '9', '21', '9', '23', '14', '21', '-13',
        '23', '11', '23', '10', '26', '6', '27'],
       ['November', 'Week 3', '9', '32', '15', '22', '13', '21', '13',
        '28', '6', '26', '15', '24', '12', '29'],
       ['November', 'Week 4', '13', '26', '6', '28', '15', '20', '9',
        '30', '13', '31', '7', '32', '15', '27']], dtype='<U9')

In [137]:
nov_diff = Nov_data[:,2:6].astype(int)
nov_diff
#selecting the nov month data of first two days

array([[ 8, 21, 11, 20],
       [ 9, 21,  9, 23],
       [ 9, 32, 15, 22],
       [13, 26,  6, 28]])

In [138]:
nov_max_diff1 = nov_diff[:,1::2]
nov_max_diff1
#selecting the nov month data of first two days of max temp data

array([[21, 20],
       [21, 23],
       [32, 22],
       [26, 28]])

In [139]:
nov_max_day1 = nov_max_diff1[:,0]
nov_max_day1 
#selecting the nov month data of first days of max temp data

array([21, 21, 32, 26])

In [140]:
nov_max_day2 = nov_max_diff1[:,1]
nov_max_day2 
#selecting the nov month data of second days of max temp data

array([20, 23, 22, 28])

In [141]:
nov_max_diff2 = np.subtract(nov_max_day2 ,nov_max_day1 ).reshape(4,1)
nov_max_diff2
#subtract the value of two days and reshaped it

array([[ -1],
       [  2],
       [-10],
       [  2]])

In [142]:
Dec_data

array([['December', 'Week 1', '7', '32', '11', '31', '8', '27', '11',
        '25', '10', '31', '6', '24', '6', '31'],
       ['December', 'Week 2', '11', '28', '11', '25', '12', '23', '13',
        '23', '6', '25', '14', '25', '14', '26'],
       ['December', 'Week 3', '8', '30', '12', '32', '6', '30', '11',
        '28', '11', '27', '15', '26', '8', '20'],
       ['December', 'Week 4', '11', '29', '11', '27', '12', '28', '10',
        '22', '11', '21', '12', '27', '10', '28']], dtype='<U9')

In [143]:
Dec_diff = Dec_data[:,2:6].astype(int)
Dec_diff
#selecting the dec month data of first two days

array([[ 7, 32, 11, 31],
       [11, 28, 11, 25],
       [ 8, 30, 12, 32],
       [11, 29, 11, 27]])

In [144]:
Dec_max_diff1 = Dec_diff[:,1::2]
Dec_max_diff1
#selecting the dec month data of first two days of max temp data

array([[32, 31],
       [28, 25],
       [30, 32],
       [29, 27]])

In [145]:
Dec_max_day1 = Dec_max_diff1[:,0]
Dec_max_day1 
#selecting the dec month data of second days of max temp data

array([32, 28, 30, 29])

In [146]:
Dec_max_day2 = Dec_max_diff1[:,1]
Dec_max_day2 
#selecting the dec month data of second days of max temp data

array([31, 25, 32, 27])

In [147]:
Dec_max_diff2 = np.subtract(Dec_max_day2 ,Dec_max_day1 ).reshape(4,1)
Dec_max_diff2
#subtract the value of two days and reshaped it

array([[-1],
       [-3],
       [ 2],
       [-2]])

In [148]:
Jan_data

array([['January', 'Week 1', '3', '19', '8', '22', '7', '18', '7', '22',
        '3', '19', '6', '8', '20', '7'],
       ['January', 'Week 2', '5', '18', '8', '19', '7', '18', '6', '19',
        '5', '18', '7', '6', '20', '5'],
       ['January', 'Week 3', '2', '22', '7', '19', '4', '22', '2', '21',
        '8', '22', '4', '2', '21', '2'],
       ['January', 'Week 4', '4', '22', '6', '18', '8', '22', '5', '18',
        '3', '22', '4', '8', '18', '7']], dtype='<U9')

In [149]:
Jan_diff = Jan_data[:,2:6].astype(int)
Jan_diff
#selecting the jan month data of first two days

array([[ 3, 19,  8, 22],
       [ 5, 18,  8, 19],
       [ 2, 22,  7, 19],
       [ 4, 22,  6, 18]])

In [150]:
Jan_max_diff1 = Jan_diff[:,1::2]
Jan_max_diff1
#selecting the jan month data of first two days of max temp data

array([[19, 22],
       [18, 19],
       [22, 19],
       [22, 18]])

In [151]:
Jan_max_day1 = Jan_max_diff1[:,0]
Jan_max_day1 
#selecting the jan month data of second days of max temp data

array([19, 18, 22, 22])

In [152]:
Jan_max_day2 = Jan_max_diff1[:,1]
Jan_max_day2 
#selecting the jan month data of second days of max temp data

array([22, 19, 19, 18])

In [153]:
Jan_max_diff2 = np.subtract(Jan_max_day2 ,Jan_max_day1 ).reshape(4,1)
Jan_max_diff2
#subtract the value of two days and reshaped it

array([[ 3],
       [ 1],
       [-3],
       [-4]])

### 24.Find and store the difference between the minimum temp of two consecutive days for each month of the winter season.

In [154]:
nov_min_diff1 = nov_diff[:,0::2]
nov_min_diff1
#selecting the nov month data of first two days of min temp data

array([[ 8, 11],
       [ 9,  9],
       [ 9, 15],
       [13,  6]])

In [155]:
nov_min_day1 = nov_min_diff1[:,0]
nov_min_day1 
#selecting the nov month data of second days of min temp data

array([ 8,  9,  9, 13])

In [156]:
nov_min_day2 = nov_min_diff1[:,1]
nov_min_day2 
#selecting the nov month data of second days of min temp data

array([11,  9, 15,  6])

In [157]:
nov_min_diff = np.subtract(nov_min_day2 ,nov_min_day1 ).reshape(4,1)
nov_min_diff
#subtract the value of two days and reshaped it

array([[ 3],
       [ 0],
       [ 6],
       [-7]])

In [158]:
Dec_min_diff1 = Dec_diff[:,0::2]
Dec_min_diff1
#selecting the dec month data of first two days of min temp data

array([[ 7, 11],
       [11, 11],
       [ 8, 12],
       [11, 11]])

In [159]:
Dec_min_day1 = Dec_min_diff1[:,0]
Dec_min_day1 
#selecting the dec month data of second days of min temp data

array([ 7, 11,  8, 11])

In [160]:
Dec_min_day2 = Dec_min_diff1[:,1]
Dec_min_day2 
#selecting the dec month data of second days of min temp data

array([11, 11, 12, 11])

In [161]:
Dec_min_diff = np.subtract(Dec_min_day2 ,Dec_min_day1 ).reshape(4,1)
Dec_min_diff
#subtract the value of two days and reshaped it

array([[4],
       [0],
       [4],
       [0]])

In [162]:
Jan_min_diff1 = Jan_diff[:,0::2]
Jan_min_diff1
#selecting the jan month data of first two days of min temp data

array([[3, 8],
       [5, 8],
       [2, 7],
       [4, 6]])

In [163]:
Jan_min_day1 = Jan_min_diff1[:,0]
Jan_min_day1 
#selecting the jan month data of second days of min temp data

array([3, 5, 2, 4])

In [164]:
Jan_min_day2 = Jan_min_diff1[:,1]
Jan_min_day2 
#selecting the jan month data of second days of min temp data

array([8, 8, 7, 6])

In [165]:
Jan_min_diff = np.subtract(Jan_min_day2 ,Jan_min_day1 ).reshape(4,1)
Jan_min_diff
#subtract the value of two days and reshaped it

array([[5],
       [3],
       [5],
       [2]])

### 25. Create an array by combining the data present in arrays created in q.23 and q.24, to store the difference between the min and max temp of each day of all the months for the whole winter season, in a single array.

In [166]:
Nov_min_max_diff = np.hstack((nov_min_diff,nov_max_diff2))
Dec_min_max_diff = np.hstack((Dec_min_diff,Dec_max_diff2))
Jan_min_max_diff = np.hstack((Jan_min_diff,Jan_max_diff2))
#print the winter months and find the difference and hstacking the all value for first two days values)

In [167]:
win_min_max_diff = np.vstack(((Nov_min_max_diff,Dec_min_max_diff,Jan_min_max_diff)))
win_min_max_diff

array([[  3,  -1],
       [  0,   2],
       [  6, -10],
       [ -7,   2],
       [  4,  -1],
       [  0,  -3],
       [  4,   2],
       [  0,  -2],
       [  5,   3],
       [  3,   1],
       [  5,  -3],
       [  2,  -4]])

In [168]:
data_25 = data[2:-4,0:2]
data_25

array([['November', 'Week 1'],
       ['November', 'Week 2'],
       ['November', 'Week 3'],
       ['November', 'Week 4'],
       ['December', 'Week 1'],
       ['December', 'Week 2'],
       ['December', 'Week 3'],
       ['December', 'Week 4'],
       ['January', 'Week 1'],
       ['January', 'Week 2'],
       ['January', 'Week 3'],
       ['January', 'Week 4']], dtype='<U9')

In [169]:
win_min_max_diff1 = np.hstack((data_25,win_min_max_diff))
win_min_max_diff1
#print all min and max temp for first two days

array([['November', 'Week 1', '3', '-1'],
       ['November', 'Week 2', '0', '2'],
       ['November', 'Week 3', '6', '-10'],
       ['November', 'Week 4', '-7', '2'],
       ['December', 'Week 1', '4', '-1'],
       ['December', 'Week 2', '0', '-3'],
       ['December', 'Week 3', '4', '2'],
       ['December', 'Week 4', '0', '-2'],
       ['January', 'Week 1', '5', '3'],
       ['January', 'Week 2', '3', '1'],
       ['January', 'Week 3', '5', '-3'],
       ['January', 'Week 4', '2', '-4']], dtype='<U11')