# Q1

In [1]:
import numpy as np

In [2]:
x = np.array([[4,2],[1,3],[2,5],[6,8]], dtype='int16')

In [3]:
x

array([[4, 2],
       [1, 3],
       [2, 5],
       [6, 8]], dtype=int16)

In [4]:
print("Shape of the array:", x.shape)
print("Dimension of the array:", x.ndim)
print("Length of each element of array in bytes:", x.itemsize)

Shape of the array: (4, 2)
Dimension of the array: 2
Length of each element of array in bytes: 2


# Q2

In [5]:
a = np.linspace(start=100, stop=200,num=10).reshape(5,2)

In [6]:
print(a)

[[100.         111.11111111]
 [122.22222222 133.33333333]
 [144.44444444 155.55555556]
 [166.66666667 177.77777778]
 [188.88888889 200.        ]]


# Q3

In [7]:
b = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [8]:
b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [9]:
b = np.delete(b,[0,1], axis =1)

In [10]:
b

array([[33],
       [66],
       [99]])

# Q4

In [11]:
c = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [12]:
c

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [13]:
c = np.delete(c, [0,2], axis=1)

In [14]:
c

array([[ 6, 12],
       [18, 24],
       [30, 36],
       [42, 48],
       [54, 60]])

In [15]:
c = np.delete(c, [1,3], axis=0)

In [16]:
c

array([[ 6, 12],
       [30, 36],
       [54, 60]])

# Q5

In [17]:
d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
d[d % 2 == 1]

array([1, 3, 5, 7, 9])

# Q6

In [19]:
a = np.zeros(10)

In [20]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Q7

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
print("Size of the array: ", x.size)
 
print("Memory size of one array element in bytes: ", x.itemsize)

Size of the array:  6
Memory size of one array element in bytes:  4


# Q8

In [24]:
x = np.zeros(10);  x[4]=1

In [25]:
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Q9

In [26]:
y = np.arange(10,50)

In [27]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Q10

In [28]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q11

In [29]:
a = np.random.random((3,3,3))
a

array([[[0.10850502, 0.55761278, 0.80380465],
        [0.72482132, 0.26645095, 0.9331459 ],
        [0.52282063, 0.8378448 , 0.23315538]],

       [[0.2632828 , 0.82118612, 0.43729459],
        [0.31272063, 0.92360755, 0.57460146],
        [0.98840695, 0.29144062, 0.69108337]],

       [[0.89278773, 0.13799365, 0.06294923],
        [0.45584036, 0.89368079, 0.02088371],
        [0.6235635 , 0.44433856, 0.20516804]]])

# Q12

In [30]:
np.__version__

'1.20.1'

In [31]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']


# Q13

In [32]:
list = [1,2,3,4,5]

In [33]:
a = np.array(list)

In [34]:
a

array([1, 2, 3, 4, 5])

# Q14

In [35]:
x =  np.linspace(start=7, stop=15, num=16).reshape(4,4)

In [36]:
x

array([[ 7.        ,  7.53333333,  8.06666667,  8.6       ],
       [ 9.13333333,  9.66666667, 10.2       , 10.73333333],
       [11.26666667, 11.8       , 12.33333333, 12.86666667],
       [13.4       , 13.93333333, 14.46666667, 15.        ]])

# Q15

In [37]:
x = np.zeros(10);  x[6]=11
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

# Q16

In [38]:
a =np.array([10,20,30,40,50])

In [39]:
a

array([10, 20, 30, 40, 50])

In [40]:
a = np.flip(a)

In [41]:
a

array([50, 40, 30, 20, 10])

# Q17

In [42]:
x = np.ones((3, 3))

In [43]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Q18

In [44]:
x = [10, 20, 30]
x = np.append(x, [[40, 50, 60], [70, 80, 90]])

In [45]:
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Q19

In [46]:
f_value = [0, 12, 24]
X = np.array(f_value)
print("Values in Fahrenheit degrees:",X)

Values in Fahrenheit degrees: [ 0 12 24]


In [47]:
x = np.round((5*X/9 - 5*32/9),2)

In [48]:
print("Values in Centigrade degrees:",x)

Values in Centigrade degrees: [-17.78 -11.11  -4.44]


# Q20

In [49]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
print("Size of the array: ", x.size)
 
print("Memory size of one array element in bytes: ", x.itemsize)

Size of the array:  6
Memory size of one array element in bytes:  4


# Q21

In [51]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
a= np.arange(0,6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

# Q22

In [56]:
x = np.array([[2, 4, 6], [6, 8, 10]])

In [57]:
x.dtype

dtype('int32')

In [58]:
y = x.astype(float)
y

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

In [59]:
y.dtype

dtype('float64')

# Q23

In [60]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
a =np.linspace(start=2, stop=5, num=20)
a

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

# Q24

In [62]:
x = np.array([[0, 10, 20], [20, 30, 40]])

In [63]:
x

array([[ 0, 10, 20],
       [20, 30, 40]])

In [64]:
np.count_nonzero(x)

5

# Q25

In [65]:
x = np.arange(1, 100)

In [66]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
y= x[(x % 3 == 0) | (x % 5 == 0)]

In [68]:
y.sum()

2318