In [1]:
import numpy as np

# Q1

In [2]:
num = list(range(10))
previousNum = 0
for i in num:
    sum = previousNum + i
    print('Current Number '+ str(i) + 'Previous Number ' + str(previousNum) + 'is ' + str(sum)) # <- This is the issue.
    previousNum=i

Current Number 0Previous Number 0is 0
Current Number 1Previous Number 0is 1
Current Number 2Previous Number 1is 3
Current Number 3Previous Number 2is 5
Current Number 4Previous Number 3is 7
Current Number 5Previous Number 4is 9
Current Number 6Previous Number 5is 11
Current Number 7Previous Number 6is 13
Current Number 8Previous Number 7is 15
Current Number 9Previous Number 8is 17


# Q2

In [3]:
str_x = "Emma is good developer. Emma is a writer"
a = str_x.count("Emma")
print(a)

2


# Q3

In [4]:
def merge_list(list1, list2):
    result_list = []

    for num in list1:
        if num % 2 != 0:
            result_list.append(num)
    
    for num in list2:
        if num % 2 == 0:
            result_list.append(num)
    return result_list

In [5]:
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
print("result list:", merge_list(list1, list2))

result list: [25, 35, 40, 60, 90]


# Q4

In [6]:
rows = 5
k = 2 * rows - 2
for i in range(0, rows):
    for j in range(0, k):
        print(end=" ")
    k = k - 2
    for j in range(0, i + 1):
        print("* ", end="")
    print("")

        * 
      * * 
    * * * 
  * * * * 
* * * * * 


In [7]:
rows = 5
for i in range(rows + 1, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print(" ")

* * * * *  
* * * *  
* * *  
* *  
*  
 


In [8]:
for num in range(10):
    for i in range(num):
        print (num, end=" ") 
    print("\n")



1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 

6 6 6 6 6 6 

7 7 7 7 7 7 7 

8 8 8 8 8 8 8 8 

9 9 9 9 9 9 9 9 9 



# Q5

In [9]:
def exponent(base, exp):
    num = exp
    result = 1
    while num > 0:
        result = result * base
        num = num - 1
    print(base, "raises to the power of", exp, "is: ", result)

exponent(2, 5)

2 raises to the power of 5 is:  32


In [10]:
exponent(5, 4)

5 raises to the power of 4 is:  625


# Q6

In [11]:
x = np.array([34, 56, 89,23, 69, 980, 567])
print(x)
print(np.all(x))

[ 34  56  89  23  69 980 567]
True


In [12]:
y = np.array([0,34, 56, 89,23, 69, 980, 567])
print(y)
print(np.all(y))

[  0  34  56  89  23  69 980 567]
False


# Q7

In [13]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Q8

In [14]:
x = np.arange(30, 71, 2)

In [15]:
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# Q9

In [16]:
x = np.array([[0,1],[2,3]])

In [17]:
x

array([[0, 1],
       [2, 3]])

In [18]:
np.sum(x)

6

In [19]:
np.sum(x, axis=0)

array([2, 4])

In [20]:
np.sum(x, axis=1)

array([1, 5])

# Q10

In [21]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Q11

In [22]:
a = np.random.randint(2,10,20).reshape(4,5)

In [23]:
a

array([[4, 2, 4, 4, 8],
       [5, 9, 5, 4, 4],
       [3, 7, 3, 9, 9],
       [3, 6, 6, 2, 5]])

In [24]:
np.sort(a)

array([[2, 4, 4, 4, 8],
       [4, 4, 5, 5, 9],
       [3, 3, 7, 9, 9],
       [2, 3, 5, 6, 6]])

In [25]:
np.sort(a, axis=0)

array([[3, 2, 3, 2, 4],
       [3, 6, 4, 4, 5],
       [4, 7, 5, 4, 8],
       [5, 9, 6, 9, 9]])

# Q12

In [26]:
a= np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 

In [27]:
a

array([[[1, 5, 2, 1],
        [4, 3, 5, 6],
        [6, 3, 0, 6],
        [7, 3, 5, 0],
        [2, 3, 3, 5]],

       [[2, 2, 3, 1],
        [4, 0, 0, 5],
        [6, 3, 2, 1],
        [5, 1, 0, 0],
        [0, 1, 9, 1]],

       [[3, 1, 4, 2],
        [4, 1, 6, 0],
        [1, 2, 0, 6],
        [8, 3, 4, 0],
        [2, 0, 2, 8]]])

# Q13

In [28]:
a = np.random.randint(2,10,20).reshape(4,5)

In [29]:
a

array([[6, 9, 8, 8, 6],
       [6, 6, 3, 5, 7],
       [5, 6, 3, 4, 7],
       [6, 7, 8, 3, 4]])

In [30]:
a= print(a[::-1, ::-1])

[[4 3 8 7 6]
 [7 4 3 6 5]
 [7 5 3 6 6]
 [6 8 8 9 6]]


# Q14

In [31]:
a = np.random.randint(2,10,20).reshape(4,5)

In [32]:
print(a)

[[2 2 3 6 5]
 [5 8 3 6 5]
 [6 7 9 6 2]
 [6 4 6 4 7]]


In [33]:
np.amin(a)

2

In [34]:
np.amin(a, axis=1)

array([2, 3, 2, 4])

# Q15

In [35]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


# Q16

In [36]:
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by second row")
print(sortArrayByRow)

print("Sorting Original array by second column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


# Q17

In [ ]:
a = np.array([[5, 6, 9], [21 ,18, 27]])
b = np.array([[15 ,33, 24], [4 ,7, 1]])

c  = a + b
print("addition of two arrays is \n")
print(c)

for num in np.nditer(c, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(c)

# Q18

In [38]:
m1 = np.arange(6).reshape(2,3)
m2 = np.array([[1,4,6],[2,3,4]])

In [39]:
np.dot(m1,m2.T)

array([[16, 11],
       [49, 38]])

# Q19

In [41]:
m2

array([[1, 4, 6],
       [2, 3, 4]])

In [40]:
np.linalg.norm(m2)

9.055385138137417

# Q20

In [42]:
m = np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [43]:
np.linalg.cond(m)

14.933034373659265

# Q21

In [44]:
m1
m2

array([[1, 4, 6],
       [2, 3, 4]])

In [45]:
m1+m2

array([[1, 5, 8],
       [5, 7, 9]])

In [46]:
m1-m2

array([[-1, -3, -4],
       [ 1,  1,  1]])

In [47]:
m1*m2

array([[ 0,  4, 12],
       [ 6, 12, 20]])

# Q22

In [48]:
x = [1., 2., 3., 4.]

In [52]:
np.floor_divide(x, 1.5)

array([0., 1., 2., 2.])

# Q23

In [54]:
a = np.arange(7)

In [55]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
np.power(a,3)

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

# Q24

In [57]:
a = np.array([1,2,3])

In [58]:
b =np.cos(a)

In [59]:
b

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [60]:
np.round(b,2)

array([ 0.54, -0.42, -0.99])

# Q25

In [61]:
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.92061142 0.4249213  0.8998051 ]
 [0.94084532 0.75944255 0.75956697]
 [0.16394939 0.16819331 0.73458822]
 [0.93094314 0.86369529 0.40306246]
 [0.4703661  0.58804761 0.88848349]]
Second array:
[[0.10538622 0.72119633]
 [0.67197837 0.38904665]
 [0.04603293 0.41987128]]
Dot product of two arrays:
[[0.42397835 1.2070581 ]
 [0.6444462  1.29291313]
 [0.16411552 0.49210723]
 [0.69704728 1.17664489]
 [0.48562488 0.94105296]]


# Q26

In [62]:
a = np.array([[10,40],[30,20]])
print("Original array:")
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


# Q27

In [63]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height')) 

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


# Q28

In [65]:
nums = np.random.randint(0,10,(3,3))
print(nums)
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

[[4 6 0]
 [8 3 9]
 [0 0 9]]

Sort the said array by the nth column: 
[[0 0 9]
 [8 3 9]
 [4 6 0]]


# Q29

In [68]:
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])

Original array:
[0.30788645 0.52533732 0.60778782 0.64891713 0.88798589 0.46094245
 0.08063686 0.35497701 0.50701498 0.24362038]

Sorted first 5 elements:
[0.08063686 0.24362038 0.30788645 0.35497701 0.46094245 0.88798589
 0.60778782 0.64891713 0.50701498 0.52533732]
