In [1]:
import csv

In [2]:
import numpy as np

In [3]:
data = []

In [4]:
with open("MER_T07_02A-2020-02-03.csv", 'r') as x:
    data = list(csv.reader(x, delimiter=","))
 
data = np.array(data)
display(data)

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [5]:
data.shape

(8217, 6)

In [6]:
data.ndim

2

In [7]:
data.dtype.type

numpy.str_

In [8]:
data[0] #slicing

array(['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
      dtype='<U80')

In [9]:
data[0:5]

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195213', '195436.666', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [10]:
top = data[0:5]

In [11]:
bottom =data[-5:]

In [12]:
np.vstack((top,bottom))

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195213', '195436.666', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201906', '351342.905', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201907', '411583.828', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
     

In [13]:
np.unique(data)

array(['-0.001', '-0.004', '-0.009', ..., 'WSETPUS', 'WYETPUS', 'YYYYMM'],
      dtype='<U80')

# 2

In [14]:
print(data[0:10, 3:4]) #Print the data contained in the first 10 rows of the 4th column.

[['Column_Order']
 ['1']
 ['1']
 ['1']
 ['1']
 ['1']
 ['1']
 ['1']
 ['1']
 ['1']]


In [15]:
print(data[0:10, :3])

[['MSN' 'YYYYMM' 'Value']
 ['CLETPUS' '194913' '135451.32']
 ['CLETPUS' '195013' '154519.994']
 ['CLETPUS' '195113' '185203.657']
 ['CLETPUS' '195213' '195436.666']
 ['CLETPUS' '195313' '218846.325']
 ['CLETPUS' '195413' '239145.966']
 ['CLETPUS' '195513' '301362.698']
 ['CLETPUS' '195613' '338503.484']
 ['CLETPUS' '195713' '346386.207']]


In [16]:
data

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

# 3

In [17]:
#Which row serves as the headers/titles for all the columns.
#0 index row

# 4

In [18]:
#Print the data contained in column 2 and 3 from row 1 till row 20

In [19]:
print(data[1:20, 1:3])

[['194913' '135451.32']
 ['195013' '154519.994']
 ['195113' '185203.657']
 ['195213' '195436.666']
 ['195313' '218846.325']
 ['195413' '239145.966']
 ['195513' '301362.698']
 ['195613' '338503.484']
 ['195713' '346386.207']
 ['195813' '344365.781']
 ['195913' '378424.21']
 ['196013' '403067.357']
 ['196113' '421870.669']
 ['196213' '450249.238']
 ['196313' '493926.719']
 ['196413' '526230.019']
 ['196513' '570925.951']
 ['196613' '613474.8']
 ['196713' '630483.363']]


# 5

In [20]:
#Print the data present in only the first three and the last three rows of all the columns in a single output.

In [21]:
top = data[0:3]

In [22]:
bottom = data[-3:]

In [23]:
np.vstack((top,bottom))

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

# 6

In [24]:
#Sort the data on the basis of net amount of electricity generated irrespective of the source.

In [25]:
data[0:,2]

array(['Value', '135451.32', '154519.994', ..., '401363.186',
       '359300.603', '321921.812'], dtype='<U80')

In [26]:
cnd_of_slec = data[0:,2]!= 'Not Available'

In [27]:
cnd_of_slec

array([ True,  True,  True, ...,  True,  True,  True])

In [28]:
cnd_of_slec.shape

(8217,)

In [29]:
x = data[cnd_of_slec]

In [30]:
x.shape

(7387, 6)

In [31]:
np.sort(x[1:,2].astype(float))

array([  -8823.445,   -8742.928,   -8535.065, ..., 4125059.9  ,
       4156744.724, 4174397.655])

In [32]:
r = x[1:,2].astype(float)

In [33]:
r.shape

(7386,)

### 10
#Print the Total Energy generated in the USA till date.

In [34]:
r

array([135451.32 , 154519.994, 185203.657, ..., 401363.186, 359300.603,
       321921.812])

In [35]:
np.sum(r)

642969289.517

In [36]:
a= data[0:,2]

In [37]:
np.sort(a) #desending sort

array(['-0.001', '-0.004', '-0.009', ..., 'Not Available',
       'Not Available', 'Value'], dtype='<U80')

# 8

In [38]:
#Print all the unique sources of Energy generation present in the dataset.

In [39]:
data[0:,4]

array(['Description', 'Electricity Net Generation From Coal, All Sectors',
       'Electricity Net Generation From Coal, All Sectors', ...,
       'Electricity Net Generation Total (including from sources not shown), All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors'],
      dtype='<U80')

In [40]:
a = data[0:,4]

In [41]:
np.unique(a).shape

(14,)

In [42]:
np.unique(a)

array(['Description', 'Electricity Net Generation From Coal, All Sectors',
       'Electricity Net Generation From Conventional Hydroelectric Power, All Sectors',
       'Electricity Net Generation From Geothermal, All Sectors',
       'Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors',
       'Electricity Net Generation From Natural Gas, All Sectors',
       'Electricity Net Generation From Nuclear Electric Power, All Sectors',
       'Electricity Net Generation From Other Gases, All Sectors',
       'Electricity Net Generation From Petroleum, All Sectors',
       'Electricity Net Generation From Solar, All Sectors',
       'Electricity Net Generation From Waste, All Sectors',
       'Electricity Net Generation From Wind, All Sectors',
       'Electricity Net Generation From Wood, All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors'],
      dtype='<U80')

# 9  
#Print all the details(annual) where the energy source is Wind Energy.

In [43]:
x.shape

(7387, 6)

In [44]:
h =x[1:]

In [45]:
y = x[1:,1]

In [46]:
y.astype(int)

array([194913, 195013, 195113, ..., 201908, 201909, 201910])

In [47]:
time = np.mod(y.astype(int),100)==13

In [48]:
time.shape

(7386,)

In [49]:
u = h[time]

In [50]:
u.shape

(728, 6)

In [51]:
u

array([['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195113', '185203.657', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201613', '4076674.984', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201713', '4034270.522', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201813', '4174397.655', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [52]:
wind_enr = u[:,4]=='Electricity Net Generation From Wind, All Sectors'

In [53]:
wind_enr.shape

(728,)

In [54]:
WE = u[wind_enr]

In [55]:
WE

array([['WYETPUS', '198313', '2.668', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198413', '6.49', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198513', '5.762', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198613', '4.189', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198713', '3.541', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198813', '0.871', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '198913', '2112.043', '12',
        'Electricity Net Generation From Wind, All Sectors',
        'Million Kilowatthours'],
       ['WYETPUS', '19901

In [56]:
n = WE[0:,2].astype(float)

In [57]:
n.shape

(36,)

In [58]:
np.sum(n) #Sum of wind energy source

1940339.685

### 11 
#Print the average annual energy generated from wind in the USA and also the standard
deviation present in the energy generation.

In [59]:
np.sum(n) #Sum of wind energy source

1940339.685

In [60]:
np.std(n)

81322.74833843806